### ISSUE TITLE
Replaying transactions does not use the same nonce

### ISSUE THREAD

**Issue by hexonaut** [makerdao/auction-demo-keeper#29]
Tested setting up a new account, and when the transaction took too long it attempted to retry with higher gas, but it used a higher nonce. You can see this in the recent txs for setup here: https://etherscan.io/address/0x3cb42106ecdfe3490648547448b2f96871298e8b

In particular [tx1](https://etherscan.io/tx/0x66403764ff9c47266065f4b9f8e8a53409708fdbd410e1b6797ac59c7be8313d) and [tx2](https://etherscan.io/tx/0xd694fbb6cc4d8c8b816e457d8a3221351e56513479a0af5b9fe834fb16341e9c) were executed in the same run with the keeper telling me it was executing tx2 as a replay to tx1 which was taking too long. As you can see the nonce has been incremented when it should have been the same.

**Comment by pcatana** [comment]
I've tried to replicate the issue on mainnet as well. 
This is the code that checks for replacement: https://github.com/makerdao/auction-demo-keeper/blob/main/src/transact.js#L140 

The nonce is kept the same if it's not mined during the timeout. However, the exception was that when it's mined and the [receipt](https://github.com/makerdao/auction-demo-keeper/blob/main/src/transact.js#L124) has not yet been defined it's submitting a new tx with new nonce. 
I'll try to fix this. 
Thanks for bringing this up.

**Comment by pcatana** [comment]
issue been fixed https://github.com/makerdao/auction-demo-keeper/commit/6fcd6370712e997802102463fc413315dd4a86a4
